name: "CI"
run-name: Deploy ${{ github.run_number}} of ${{ github.repository }}, started by ${{ github.actor }}
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Auto version and tag
        id: version
        uses: svenskkod-io/github-actions/.github/actions/auto-version-tag@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/svenskkod-io/utodo-backend
          tags: |
            type=raw,value=${{ steps.version.outputs.BUILD_VERSION }}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            build_version=${{ steps.version.outputs.BUILD_VERSION }}
          cache-from: type=gha,scope=build
          cache-to: type=gha,scope=build,mode=max

      - name: Deploy to Kubernetes
        uses: svenskkod-io/github-actions/.github/actions/k8s-deploy@main
        with:
          working-directory: "backend"
          namespace: utodo
          deployment-name: utodo-backend
          build-version: ${{ steps.version.outputs.BUILD_VERSION }}
          kubeconfig: ${{ secrets.DIGITALOCEAN_CLUSTER_CONFIG }}
